steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/k12-edu-ai-media-generator:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/k12-edu-ai-media-generator:$COMMIT_SHA']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'k12-edu-ai-media-generator-gpu'
      - '--image=gcr.io/$PROJECT_ID/k12-edu-ai-media-generator:$COMMIT_SHA'
      - '--region=asia-southeast1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--port=3000'
      - '--memory=16Gi'
      - '--cpu=8'
      - '--min-instances=1'
      - '--max-instances=2'
      - '--timeout=1200'
      - '--service-account=ai-service@oneclasscomputex.iam.gserviceaccount.com'
      - '--set-env-vars=GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/credentials.json'
      - '--labels=run.googleapis.com/cpu-throttling=false,run.googleapis.com/startup-cpu-boost=true'
      #- '--gpu=1'
      #- '--gpu-type=nvidia-l4'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/k12-edu-ai-media-generator:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/k12-edu-ai-media-generator:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/k12-edu-ai-media-generator:latest']
images:
  - 'gcr.io/$PROJECT_ID/k12-edu-ai-media-generator:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/k12-edu-ai-media-generator:latest'
options:
  logging: CLOUD_LOGGING_ONLY